### ISSUE TITLE
Alle Daten in der Postgres Datenbank

### ISSUE THREAD

**Issue by LinkAlexander** [LinkAlexander/VISHCI#2]
Alle Daten müssen per Postgres abfragbar sein. Dafür müssen die TSV-Dateien eingespeist werden und mit den richtigen Datentypen versehen werden.

**Comment by RebornStreicherJo** [comment]
- [x] Daten korregieren
- [ ] Null-Werte (\N) als diese lesen
- [ ] Korrekte Datentypen
- [ ] Nicht alle Daten im RAM gleichzeitig
