### ISSUE TITLE
Karte perfektionieren

### ISSUE THREAD

**Issue by LinkAlexander** [LinkAlexander/VISHCI#4]
Der Globus steht schon. Es ist wichtig, dass Landspezifische Daten eingespeist werden können

**Comment by RebornStreicherJo** [comment]
Der Stand sieht wie folgt aus:
- Daten nach avg rating können länderspezifisch eingeladen werden
- Die Skalen für min und maxValue können im Frontend angepasst werden

![grafik](https://github.com/LinkAlexander/VISHCI/assets/167143907/87c73025-4fc8-4cc2-89ee-7eee923b9fc8)

**Comment by RebornStreicherJo** [comment]
- [x] Legende machen: Wofür stehen die Farben (Grün/Rot)
- [x] Slider: Start-Jahr bis End-Jahr
- [x] Prüfen: Farbberechnung mit relativen Werten
- [x] Porn toggle (isAdult)

**Comment by LinkAlexander** [comment]
Karte ist erstmal fertig!

![image](https://github.com/LinkAlexander/VISHCI/assets/93796836/aabe8413-121c-46f0-b7f5-f40373e488a2)
![image](https://github.com/LinkAlexander/VISHCI/assets/93796836/c0d23a3f-95cb-4b4d-a3cd-2c6e3fb6305e)
![image](https://github.com/LinkAlexander/VISHCI/assets/93796836/436a0496-c87b-4310-baef-0d49cc7b4705)
![image](https://github.com/LinkAlexander/VISHCI/assets/93796836/76f19b77-8b6e-48ea-950f-1aee66fea9e6)
